package com.design.entity;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.click_count
     *
     * @mbggenerated
     */
    private String clickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.reply_count
     *
     * @mbggenerated
     */
    private String replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.like_count
     *
     * @mbggenerated
     */
    private String likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_image
     *
     * @mbggenerated
     */
    private String blogImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.reprint
     *
     * @mbggenerated
     */
    private String reprint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.summary
     *
     * @return the value of blog.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.summary
     *
     * @param summary the value for blog.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_date
     *
     * @return the value of blog.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_date
     *
     * @param createDate the value for blog.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_date
     *
     * @return the value of blog.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_date
     *
     * @param updateDate the value for blog.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.click_count
     *
     * @return the value of blog.click_count
     *
     * @mbggenerated
     */
    public String getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.click_count
     *
     * @param clickCount the value for blog.click_count
     *
     * @mbggenerated
     */
    public void setClickCount(String clickCount) {
        this.clickCount = clickCount == null ? null : clickCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.reply_count
     *
     * @return the value of blog.reply_count
     *
     * @mbggenerated
     */
    public String getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.reply_count
     *
     * @param replyCount the value for blog.reply_count
     *
     * @mbggenerated
     */
    public void setReplyCount(String replyCount) {
        this.replyCount = replyCount == null ? null : replyCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.like_count
     *
     * @return the value of blog.like_count
     *
     * @mbggenerated
     */
    public String getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.like_count
     *
     * @param likeCount the value for blog.like_count
     *
     * @mbggenerated
     */
    public void setLikeCount(String likeCount) {
        this.likeCount = likeCount == null ? null : likeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.type_id
     *
     * @return the value of blog.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.type_id
     *
     * @param typeId the value for blog.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_image
     *
     * @return the value of blog.blog_image
     *
     * @mbggenerated
     */
    public String getBlogImage() {
        return blogImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_image
     *
     * @param blogImage the value for blog.blog_image
     *
     * @mbggenerated
     */
    public void setBlogImage(String blogImage) {
        this.blogImage = blogImage == null ? null : blogImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.reprint
     *
     * @return the value of blog.reprint
     *
     * @mbggenerated
     */
    public String getReprint() {
        return reprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.reprint
     *
     * @param reprint the value for blog.reprint
     *
     * @mbggenerated
     */
    public void setReprint(String reprint) {
        this.reprint = reprint == null ? null : reprint.trim();
    }
}