package com.design.entity;

public class SemesterType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column semester_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column semester_type.semester
     *
     * @mbggenerated
     */
    private String semester;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column semester_type.id
     *
     * @return the value of semester_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column semester_type.id
     *
     * @param id the value for semester_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column semester_type.semester
     *
     * @return the value of semester_type.semester
     *
     * @mbggenerated
     */
    public String getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column semester_type.semester
     *
     * @param semester the value for semester_type.semester
     *
     * @mbggenerated
     */
    public void setSemester(String semester) {
        this.semester = semester == null ? null : semester.trim();
    }
}