package com.design.entity;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_title
     *
     * @mbggenerated
     */
    private String topicTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_course
     *
     * @mbggenerated
     */
    private String topicCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_semester
     *
     * @mbggenerated
     */
    private String topicSemester;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_type
     *
     * @mbggenerated
     */
    private String topicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_source
     *
     * @mbggenerated
     */
    private String topicSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_integrated_curriculum
     *
     * @mbggenerated
     */
    private String topicIntegratedCurriculum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_content
     *
     * @mbggenerated
     */
    private String topicContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_requirements
     *
     * @mbggenerated
     */
    private String topicRequirements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_main_difficulties
     *
     * @mbggenerated
     */
    private String topicMainDifficulties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.teacher_name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_status
     *
     * @mbggenerated
     */
    private String topicStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_title
     *
     * @return the value of topic.topic_title
     *
     * @mbggenerated
     */
    public String getTopicTitle() {
        return topicTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_title
     *
     * @param topicTitle the value for topic.topic_title
     *
     * @mbggenerated
     */
    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle == null ? null : topicTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_course
     *
     * @return the value of topic.topic_course
     *
     * @mbggenerated
     */
    public String getTopicCourse() {
        return topicCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_course
     *
     * @param topicCourse the value for topic.topic_course
     *
     * @mbggenerated
     */
    public void setTopicCourse(String topicCourse) {
        this.topicCourse = topicCourse == null ? null : topicCourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_semester
     *
     * @return the value of topic.topic_semester
     *
     * @mbggenerated
     */
    public String getTopicSemester() {
        return topicSemester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_semester
     *
     * @param topicSemester the value for topic.topic_semester
     *
     * @mbggenerated
     */
    public void setTopicSemester(String topicSemester) {
        this.topicSemester = topicSemester == null ? null : topicSemester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_type
     *
     * @return the value of topic.topic_type
     *
     * @mbggenerated
     */
    public String getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_type
     *
     * @param topicType the value for topic.topic_type
     *
     * @mbggenerated
     */
    public void setTopicType(String topicType) {
        this.topicType = topicType == null ? null : topicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_source
     *
     * @return the value of topic.topic_source
     *
     * @mbggenerated
     */
    public String getTopicSource() {
        return topicSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_source
     *
     * @param topicSource the value for topic.topic_source
     *
     * @mbggenerated
     */
    public void setTopicSource(String topicSource) {
        this.topicSource = topicSource == null ? null : topicSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_integrated_curriculum
     *
     * @return the value of topic.topic_integrated_curriculum
     *
     * @mbggenerated
     */
    public String getTopicIntegratedCurriculum() {
        return topicIntegratedCurriculum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_integrated_curriculum
     *
     * @param topicIntegratedCurriculum the value for topic.topic_integrated_curriculum
     *
     * @mbggenerated
     */
    public void setTopicIntegratedCurriculum(String topicIntegratedCurriculum) {
        this.topicIntegratedCurriculum = topicIntegratedCurriculum == null ? null : topicIntegratedCurriculum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_content
     *
     * @return the value of topic.topic_content
     *
     * @mbggenerated
     */
    public String getTopicContent() {
        return topicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_content
     *
     * @param topicContent the value for topic.topic_content
     *
     * @mbggenerated
     */
    public void setTopicContent(String topicContent) {
        this.topicContent = topicContent == null ? null : topicContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_requirements
     *
     * @return the value of topic.topic_requirements
     *
     * @mbggenerated
     */
    public String getTopicRequirements() {
        return topicRequirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_requirements
     *
     * @param topicRequirements the value for topic.topic_requirements
     *
     * @mbggenerated
     */
    public void setTopicRequirements(String topicRequirements) {
        this.topicRequirements = topicRequirements == null ? null : topicRequirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_main_difficulties
     *
     * @return the value of topic.topic_main_difficulties
     *
     * @mbggenerated
     */
    public String getTopicMainDifficulties() {
        return topicMainDifficulties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_main_difficulties
     *
     * @param topicMainDifficulties the value for topic.topic_main_difficulties
     *
     * @mbggenerated
     */
    public void setTopicMainDifficulties(String topicMainDifficulties) {
        this.topicMainDifficulties = topicMainDifficulties == null ? null : topicMainDifficulties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.teacher_name
     *
     * @return the value of topic.teacher_name
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.teacher_name
     *
     * @param teacherName the value for topic.teacher_name
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_status
     *
     * @return the value of topic.topic_status
     *
     * @mbggenerated
     */
    public String getTopicStatus() {
        return topicStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_status
     *
     * @param topicStatus the value for topic.topic_status
     *
     * @mbggenerated
     */
    public void setTopicStatus(String topicStatus) {
        this.topicStatus = topicStatus == null ? null : topicStatus.trim();
    }
}