package com.design.entity;

public class TopicGuidances {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_guidances.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_guidances.topic_guidance
     *
     * @mbggenerated
     */
    private String topicGuidance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_guidances.topic_id
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_guidances.id
     *
     * @return the value of topic_guidances.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_guidances.id
     *
     * @param id the value for topic_guidances.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_guidances.topic_guidance
     *
     * @return the value of topic_guidances.topic_guidance
     *
     * @mbggenerated
     */
    public String getTopicGuidance() {
        return topicGuidance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_guidances.topic_guidance
     *
     * @param topicGuidance the value for topic_guidances.topic_guidance
     *
     * @mbggenerated
     */
    public void setTopicGuidance(String topicGuidance) {
        this.topicGuidance = topicGuidance == null ? null : topicGuidance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_guidances.topic_id
     *
     * @return the value of topic_guidances.topic_id
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_guidances.topic_id
     *
     * @param topicId the value for topic_guidances.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }
}