package com.design.dao;

import com.design.entity.ClassType;
import com.design.entity.ClassTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ClassTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int countByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int deleteByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from class_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into class_type (id, class_name)",
        "values (#{id,jdbcType=INTEGER}, #{className,jdbcType=VARCHAR})"
    })
    int insert(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int insertSelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    List<ClassType> selectByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, class_name",
        "from class_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ClassType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Update({
        "update class_type",
        "set class_name = #{className,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ClassType record);
}