package com.design.dao;

import com.design.entity.ClassType;
import com.design.entity.ClassTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int countByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int deleteByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int insert(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int insertSelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    List<ClassType> selectByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    ClassType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassType record);
}