package com.design.dao;

import com.design.entity.CourseType;
import com.design.entity.CourseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int countByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int deleteByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int insert(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int insertSelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    List<CourseType> selectByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    CourseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseType record);
}