package com.design.dao;

import com.design.entity.SemesterType;
import com.design.entity.SemesterTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SemesterTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int countByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int deleteByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from semester_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into semester_type (id, semester)",
        "values (#{id,jdbcType=INTEGER}, #{semester,jdbcType=VARCHAR})"
    })
    int insert(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int insertSelective(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    List<SemesterType> selectByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, semester",
        "from semester_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SemesterType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SemesterType record, @Param("example") SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SemesterType record, @Param("example") SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    @Update({
        "update semester_type",
        "set semester = #{semester,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SemesterType record);
}