package com.design.dao;

import com.design.entity.SemesterType;
import com.design.entity.SemesterTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SemesterTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int countByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int deleteByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int insert(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int insertSelective(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    List<SemesterType> selectByExample(SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    SemesterType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SemesterType record, @Param("example") SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SemesterType record, @Param("example") SemesterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SemesterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SemesterType record);
}